// client/src/pages/ChatPage.tsx
import { useEffect } from 'react';
import MainLayout from '../components/layout/MainLayout';
import ChatWindow from '../components/chat/ChatWindow';
import { useAppStore } from '../stores/appStore';
import { useChatStore } from '../stores/chatStore';

export default function ChatPage() {
  const fetchChatAssistants = useAppStore((s) => s.fetchChatAssistants);
  const selectedAssistantId = useAppStore((s) => s.selectedAssistantId);
  const fetchConversations = useChatStore((s) => s.fetchConversations);

  // Load chat assistants on mount
  useEffect(() => {
    fetchChatAssistants();
  }, []);

  // Load conversations when assistant changes
  useEffect(() => {
    if (selectedAssistantId) {
      fetchConversations(selectedAssistantId);
    }
  }, [selectedAssistantId]);

  return (
    <MainLayout>
      <ChatWindow />
    </MainLayout>
  );
}

// client/src/pages/ChatPage.vue
<script setup lang="ts">
// 对应原 client/src/pages/ChatPage.tsx
import { onMounted, watch } from 'vue';
import MainLayout from '../components/layout/MainLayout.vue';
import ChatWindow from '../components/chat/ChatWindow.vue';
import { useAppStore } from '../stores/app';
import { useChatStore } from '../stores/chat';

const appStore = useAppStore();
const chatStore = useChatStore();

// 对应原 useEffect：挂载时加载 chat assistants
onMounted(() => {
  appStore.fetchChatAssistants();
});

// 对应原 useEffect：assistant 变化时加载 conversations
watch(
  () => appStore.selectedAssistantId,
  (id) => {
    if (id) {
      chatStore.fetchConversations(id);
    }
  }
);
</script>

<template>
  <MainLayout>
    <ChatWindow />
  </MainLayout>
</template>
