// client/src/components/chat/ChatWindow.vue
<script setup lang="ts">
// 对应原 client/src/components/chat/ChatWindow.tsx
import { computed, ref } from 'vue';
import { Empty } from 'ant-design-vue';
import { MessageOutlined } from '@ant-design/icons-vue';
import ChatHeader from './ChatHeader.vue';
import MessageList from './MessageList.vue';
import ChatInput from './ChatInput.vue';
import { useChatStore } from '../../stores/chat';
import { useAppStore } from '../../stores/app';
import { streamChat } from '../../services/sse';

const chatStore = useChatStore();
const appStore = useAppStore();

// 对应原 useState(sending) / useRef(abortRef)
const sending = ref(false);
const abortRef = ref<AbortController | null>(null);

// 对应原 currentConv = conversations.find(...)
const currentConv = computed(() =>
  chatStore.conversations.find((c) => c.id === chatStore.currentConversationId)
);

const emptyDescription = computed(() =>
  appStore.selectedAssistantName ? '选择或新建一个对话开始问答' : '请先在左侧选择一个知识库'
);

// 对应原 handleSend（useCallback）
function handleSend(content: string) {
  if (!chatStore.currentConversationId) return;

  sending.value = true;
  chatStore.setIsStreaming(true);

  // Optimistic user message
  const userMsg = {
    id: `user-${Date.now()}`,
    conversation_id: chatStore.currentConversationId,
    role: 'user' as const,
    content,
    references: null,
    created_at: new Date().toISOString(),
  };
  chatStore.addMessage(userMsg);

  const controller = streamChat(chatStore.currentConversationId, content, (chunk) => {
    if (chunk.error) {
      chatStore.appendStreamContent(`\n\n[错误: ${chunk.error}]`);
      chatStore.setIsStreaming(false);
      sending.value = false;
      return;
    }

    if (chunk.done) {
      chatStore.setIsStreaming(false);
      sending.value = false;
      return;
    }

    chatStore.appendStreamContent(chunk.content);
  });

  abortRef.value = controller;
}
</script>

<template>
  <!-- 对应原 ChatWindow.tsx：无会话时显示 Empty（image 用插槽渲染 MessageOutlined） -->
  <div
    v-if="!chatStore.currentConversationId || !currentConv"
    class="chat-window chat-window--empty"
  >
    <Empty :description="emptyDescription">
      <template #image>
        <MessageOutlined style="font-size: 64px; color: #d9d9d9" />
      </template>
    </Empty>
  </div>

  <div v-else class="chat-window">
    <ChatHeader
      :conversation-name="currentConv.name"
      :kb-name="currentConv.kb_name || appStore.selectedKbName || ''"
    />
    <MessageList
      :messages="chatStore.messages"
      :streaming-content="chatStore.streamingContent"
      :is-streaming="chatStore.isStreaming"
    />
    <ChatInput
      :on-send="handleSend"
      :disabled="chatStore.isStreaming || sending"
    />
  </div>
</template>

<style scoped>
/* 对应原 ChatWindow.tsx 的内联样式 */
.chat-window {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: #fff;
}

.chat-window--empty {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  background: #fff;
}
</style>

// client/src/components/chat/ChatWindow.tsx
import { Empty } from 'antd';
import { MessageOutlined } from '@ant-design/icons';
import ChatHeader from './ChatHeader';
import MessageList from './MessageList';
import ChatInput from './ChatInput';
import { useChatStore } from '../../stores/chatStore';
import { useAppStore } from '../../stores/appStore';
import { streamChat } from '../../services/sse';
import { useState, useRef, useCallback } from 'react';

export default function ChatWindow() {
  const currentConvId = useChatStore((s) => s.currentConversationId);
  const conversations = useChatStore((s) => s.conversations);
  const messages = useChatStore((s) => s.messages);
  const streamingContent = useChatStore((s) => s.streamingContent);
  const isStreaming = useChatStore((s) => s.isStreaming);
  const addMessage = useChatStore((s) => s.addMessage);
  const appendStreamContent = useChatStore((s) => s.appendStreamContent);
  const setIsStreaming = useChatStore((s) => s.setIsStreaming);
  const resetStreaming = useChatStore((s) => s.resetStreaming);

  const selectedAssistantName = useAppStore((s) => s.selectedAssistantName);
  const selectedKbName = useAppStore((s) => s.selectedKbName);

  const [sending, setSending] = useState(false);
  const abortRef = useRef<AbortController | null>(null);

  const currentConv = conversations.find((c) => c.id === currentConvId);

  const handleSend = useCallback(
    (content: string) => {
      if (!currentConvId) return;

      setSending(true);
      setIsStreaming(true);

      // Optimistic user message
      const userMsg = {
        id: `user-${Date.now()}`,
        conversation_id: currentConvId,
        role: 'user' as const,
        content,
        references: null,
        created_at: new Date().toISOString(),
      };
      addMessage(userMsg);

      const controller = streamChat(currentConvId, content, (chunk) => {
        if (chunk.error) {
          appendStreamContent(`\n\n[错误: ${chunk.error}]`);
          setIsStreaming(false);
          setSending(false);
          return;
        }

        if (chunk.done) {
          setIsStreaming(false);
          setSending(false);
          return;
        }

        appendStreamContent(chunk.content);
      });

      abortRef.current = controller;
    },
    [currentConvId]
  );

  // No conversation selected
  if (!currentConvId || !currentConv) {
    return (
      <div
        style={{
          flex: 1,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexDirection: 'column',
          background: '#fff',
        }}
      >
        <Empty
          image={<MessageOutlined style={{ fontSize: 64, color: '#d9d9d9' }} />}
          description={
            selectedAssistantName
              ? '选择或新建一个对话开始问答'
              : '请先在左侧选择一个知识库'
          }
        />
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', background: '#fff' }}>
      <ChatHeader
        conversationName={currentConv.name}
        kbName={currentConv.kb_name || selectedKbName || ''}
      />
      <MessageList
        messages={messages}
        streamingContent={streamingContent}
        isStreaming={isStreaming}
      />
      <ChatInput onSend={handleSend} disabled={isStreaming || sending} />
    </div>
  );
}
